name: 0p5.dev
services:
  webapp:
    image: node:24-alpine
    container_name: 0p5.dev
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: host
    command: sh -c "npm install && npm run dev"
    env_file:
      - .env
